name: flutter_first_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  form_field_validator: ^1.0.1
    
  english_words: ^4.0.0
  provider: ^6.0.0
  go_router: ^10.0.0
  http: ^1.1.0
  dio: ^5.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/asset/images/
  